config/routes.rb
 Rails.application.routes.draw do
    mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  devise_for :users, controllers: { registrations: "registrations", omniauth_callbacks: 'users/omniauth_callbacks' }

  root to: 'pages#home'
  resources :profiles, only: [:edit, :update, :new, :create, :show]

  resources :games, only: [:show] do
    resources :ratings, only: :create
  end

  get "games", to: "games#index"
end

app/models/appearance.rb
class Appearance < ApplicationRecord
  belongs_to :player
  belongs_to :team
  belongs_to :game
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game.rb
class Game < ApplicationRecord
  belongs_to :local_team, class_name: "Team"
  belongs_to :visitor_team, class_name: "Team"
  has_many :appearances

end

app/models/player.rb
class Player < ApplicationRecord

  belongs_to :team, optional: true
  has_many :appearances
  has_many :ratings, dependent: :destroy

  validates :last_name, presence: true

end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
  belongs_to :team, optional: true
end

app/models/rating.rb
class Rating < ApplicationRecord
  belongs_to :game
  belongs_to :player
  belongs_to :user

  validates :score, :inclusion => 0..10
end

app/models/team.rb
class Team < ApplicationRecord
  has_many :players
  has_many :appearances

  validates :name, presence: true, uniqueness: true

end

app/models/user.rb
class User < ApplicationRecord
  after_create :build_profile

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, omniauth_providers: [:facebook]

  has_one :profile
  has_one :team, through: :profile
  has_many :ratings



  def self.find_for_facebook_oauth(auth)
    user_params = auth.slice(:provider, :uid)
    user_params.merge! auth.info.slice(:email)
    user_params[:facebook_picture_url] = auth.info.image
    user_params[:token] = auth.credentials.token
    user_params[:token_expiry] = Time.at(auth.credentials.expires_at)
    user_params = user_params.to_h

    user = User.find_by(provider: auth.provider, uid: auth.uid)
    user ||= User.find_by(email: auth.info.email) # User did a regular sign up in the past.
    if user
      user.update(user_params)
    else
      user = User.new(user_params)
      user.password = Devise.friendly_token[0,20]  # Fake password for validation
      user.save
    end

    return user
  end


  def build_profile
    Profile.create(user: self) # Associations must be defined correctly for this syntax, avoids using ID's directly.
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!

  def after_sign_in_path_for(resource)
    games_path
  end

  def after_sign_up_path_for(resource_or_scope)
    new_profile_path
  end

end

app/controllers/games_controller.rb
class GamesController < ApplicationController

  def index
    @games = Game.where(local_team: current_user.profile.team)
                  .or(Game.where(visitor_team: current_user.profile.team)).order("datetime DESC")
    @visitor = Team.all.sample
    @home = Team.all.sample
  end

  def show
    @game = Game.find(params[:id])

    @local_team_players = @game.appearances.select {|x| x.team_id == @game.local_team_id}
    @visitor_team_players = @game.appearances.select {|x| x.team_id == @game.visitor_team_id}
    @rating = Rating.new
  end

   def team_id
     @games = Game.where(team_id: current_user.team) #(profile(team_id))
   end


end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController

#   def index
#   # @players = Player.where(local_team: current_user.profile.team)
#   #                 .or(Game.where(visitor_team: current_user.profile.team))
#   end

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController

  before_action :teams_collection, only: [:edit, :new]
  before_action :find_profiles, only: [:edit, :update, :show]

  def show
  end

  def new
    @profile = Profile.new

  end

  def create
    @profile = Profile.new(profiles_params)
    @profile.user = current_user
    @profile.save
    redirect_to games_path
  end

  def edit
    # @profile = Profile.find(params[:id])

  end

  def update
    @profile.update(profiles_params)
    flash[:notice] = "You're so Smart. You Updated your profile"
    redirect_to games_path
  end

  private

  def profiles_params
    params.require(:profile).permit(:team_id, :last_name, :first_name)
  end

  def find_profiles
    @profile = current_user.profile
  end

  def teams_collection
    @teams = Team.all.map { |team| [team.name, team.id] }
  end
end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController

def create
  @game = Game.find(params[:game_id])
  score = params[:stars].keys.map(&:to_i).max
  player = Player.find params[:player_id]
  @rating = Rating.new
  @rating.game = @game
  @rating.user = current_user
  @rating.player = player
  @rating.score = score

  if @rating.save
    flash[:notice] = "Yeay"
    redirect_to game_path(@game)
  else
    flash[:notice] = "An error occured"
        redirect_to game_path(@game)
    end
  end


  private


  def rating_params
    # *Strong params*: You need to *whitelist* what can be updated by the user
    # Never trust user data!
    params.require(:rating).permit(:score, :player_id )
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  protected

  def after_sign_up_path_for(resource)
    new_profile_path
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    user = User.find_for_facebook_oauth(request.env['omniauth.auth'])

    if user.persisted?
      sign_in_and_redirect user, event: :authentication
      set_flash_message(:notice, :success, kind: 'Facebook') if is_navigational_format?
    else
      session['devise.facebook_data'] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/games/_playercard.html.erb
<div class="playercard text-center">
  <div class="banner_2"></div>
  <% if vplayer.player.image.present? %>

  <div class="photo_1" style="background-image: url('<%= image_path vplayer.player.image %>');"></div>
  <% end %>
  <ul class="list-unstyled playertitle">
    <div class="police_1">
      <li><b> </b></li>
      <li><%= vplayer.player.last_name unless vplayer.player.last_name.nil? %></li>
    </div>
  </ul>
  <% if vplayer.player.ratings.where(game_id: @game.id, user: current_user).blank? %>
      <%= simple_form_for([@game, @rating], method: :post, html: { class: "rating-widget"}) do |f|  %>

        <input type="hidden" name="player_id" value="<%= vplayer.player.id %>">
        <input type="checkbox" name="stars[1]" class="star-input" id="1"/>
        <label class="star-input-label" for="1">1
          <i class="fa fa-star"></i>
          <i class="fa fa-star orange"></i>
        </label>
        <input type="checkbox" name="stars[2]" class="star-input" id="2"/>
        <label class="star-input-label" for="2">2
          <i class="fa fa-star"></i>
          <i class="fa fa-star orange"></i>
        </label>
        <input type="checkbox" name="stars[3]" class="star-input" id="3"/>
        <label class="star-input-label" for="3">3
          <i class="fa fa-star"></i>
          <i class="fa fa-star orange"></i>
        </label>
        <input type="checkbox" name="stars[4]" class="star-input" id="4"/>
        <label class="star-input-label" for="4">4
          <i class="fa fa-star"></i>
          <i class="fa fa-star orange"></i>
        </label>
        <input type="checkbox" name="stars[5]" class="star-input" id="5"/>
        <label class="star-input-label" for="5">5
          <i class="fa fa-star"></i>
          <i class="fa fa-star orange"></i>
        </label>
        <input type="checkbox" name="stars[6]" class="star-input" id="6"/>
        <label class="star-input-label" for="6">6
          <i class="fa fa-star"></i>
          <i class="fa fa-star orange"></i>
        </label>
        <input type="checkbox" name="stars[7]" class="star-input" id="7"/>
        <label class="star-input-label" for="7">7
          <i class="fa fa-star"></i>
          <i class="fa fa-star orange"></i>
        </label>
        <input type="checkbox" name="stars[8]" class="star-input" id="8"/>
        <label class="star-input-label" for="8">8
          <i class="fa fa-star"></i>
          <i class="fa fa-star orange"></i>
        </label>
        <input type="checkbox" name="stars[9]" class="star-input" id="9"/>
        <label class="star-input-label" for="9">9
          <i class="fa fa-star"></i>
          <i class="fa fa-star orange"></i>
        </label>
        <input type="checkbox" name="stars[10]" class="star-input" id="10"/>
        <label class="star-input-label" for="10">10
          <i class="fa fa-star"></i>
          <i class="fa fa-star orange"></i>
        </label>
        <%= f.submit %>
      <% end %>
    <% else %>
      <p> Global rating: <%= vplayer.player.ratings.where(game_id: @game.id).inject(0){|sum,x| sum + x.score.to_i } / vplayer.player.ratings.where(game_id: @game.id).count %> </p>

      <p> Your rating: <%= vplayer.player.ratings.where(game_id: @game.id, user: current_user)[0].score %> </p>
    <% end %>
  <div class="items">
    <button class="contact" id="main-button">Last</button>
    <button class="contact" id="main-button">Next</button>
  </div>
</div>

app/views/games/index.html.erb
<h2><center>Ligue 1</center></h2>
<div class="game-cards">

<% @games.each do |g| %>
<%= link_to game_path(g) do %>
<div class="container">
  <div class="row bannerh">
    <div class="col-sm-4">
      <div class="text-left"><%= "Ligue 1, 25 journée " %>
      </div>
    </div>
    <div class="col-sm-4">
    <div class="text-center score_top">PSG Parc des Princes</div>
    </div>
    <div class="col-sm-4">
      <div class="text-right"><%= g.datetime %>
      </div>
    </div>
  </div>


  <div class="row background">
    <div class="margintop">

      <div class="row flextry spaced">
        <div class="col-sm-4">
          <div class="card_2 text-center flexed">
            <ul>
              <li>
                <div class="police">
                  <%= g.visitor_team.name %>
                </div>
              </li>
              <li>
                <%= image_tag "#{g.visitor_team.logo_path}" %>
              </li>
              <li>
                <div class="card_4 text-center">
                  <%= "Lacazette" %>
                </div>
              </li>
            </ul>
          </div>
        </div>

          <div class="flextry flexed score margintop_1"><%= g.visitor_team_score %></div>
          <div class="flextry flexed score margintop_1"><%= g.local_team_score%></div>


        <div class="col-sm-4">
          <div class="card_2 text-center flexed">
            <ul>
              <li>
                <div class="police">
                  <%= g.local_team.name %>
                </div>
              </li>
              <li>
               <%= image_tag "#{g.local_team.logo_path}" %>
             </li>
             <li>
              <div class="card_4 text-center">
                <%= "Cavani" %>
              </div>
            </li>
          </ul>
        </div>
      </div>
    </div>


  </div>
</div>
</div>

<% end %>
</div>


<br><br><br>
<% end %>
</div>

app/views/games/show.html.erb
<div class="container">
  <div class="row text-center">
    <div class="col-xs-12 col-sm-4 col-sm-offset-4">
      <div class="tabs flexy">
        <a class="tab active" data-target="#localteam">
          <h3>Local team</h3>
        </a>
        <a class="tab" data-target="#visitorteam">
          <h3>Visitor team</h3>
        </a>
      </div>
    </div>
  </div>
  <div class="row">

    <div class="text-center">
      <div class="tab-content" id="localteam">
        <div class="container">
          <div class="row">
            <div class="col-lg-12">
              <h1>Rating Players</h1>
            </div>
          </div>
          <div class="row">
           <% @local_team_players.each do  |vplayer| %>
           <div class="col-md-4 col-sm-6 col-xs-12">
             <%= render "playercard", vplayer: vplayer %>
           </div>
           <% end %>
         </div>
       </div>
     </div>
     <div class="tab-content hidden" id="visitorteam">
      <% @visitor_team_players.each do |vplayer| %>
      <div class="col-md-4 col-sm-6 col-xs-12">
       <%= render "playercard", vplayer: vplayer %>
     </div>
     <% end %>
   </div>
 </div>


</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Foot H4ckers</title>
  <%= favicon_link_tag 'logofav.png' %>
  <%= csrf_meta_tags %>
  <%= action_cable_meta_tag %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <%= stylesheet_link_tag    'application', media: 'all' %>
</head>
<body class="Site">
  <div class="wrapper">
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>

    <div class=" Site-content">
      <%= yield %>
    </div>

    <%= render 'shared/footer' %>
    <%= javascript_include_tag 'application' %>
  </div>
</body>
</html>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url(<%= image_url 'background.jpg' %>);">

  <div class="banner-content">
    <h2><center>RATE|SHARE|COMPARE</center><h2>
    <h3><center>Foot Hacker is to Football Players what IMDB is to Movies</center><h3>
    <div class="text-center">
    <p> Pick your Football Club. Watch the game. Rate 0-10 Football Players.<br>Share your Ratings on Social Media. Compare your ratings with others.</p>

      <%= link_to "SIGN UP", new_user_registration_path, class: "btn btn-success btn-lg"%>
      <%= link_to "SIGN IN", new_user_session_path, class: "btn btn-primary btn-lg"%>


    </div>
  </div>
</div>

app/views/profiles/edit.html.erb
<div class="container height-inherit overflow-auto form-container ">
  <h1 class="text-center">Edit Profile</h1>
  <h3>Personal info</h3>
  <%= simple_form_for @profile do |f| %>
    <%= f.error_notification %>
    <%= f.input :first_name %>
    <%= f.input :last_name %>
    <%= f.input :team_id, collection: @teams %>
    <%= f.button :submit, "Update" %>
  <% end %>
</div>

app/views/profiles/new.html.erb
<h1>CHOOSE YOUR FOOTBALL TEAM, PLEASE</h1>

<%= simple_form_for [@profile] do |f| %>
  <%= f.input :team_id, collection: @teams %>
  <%= f.submit "Choose this team", class: "btn btn-primary" %>
<% end %>



<!-- [@profile] -->

app/views/profiles/show.html.erb
show.html.erb

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div id="footer">
  <span class="footer-left">
    Join Us:
    <a href="https://www.youtube.com/?hl=FR"><i class="fa fa-youtube"></i></a>
    <a href="https://www.instagram.com/?hl=fr"><i class="fa fa-instagram"></i></a>
    <a href="https://www.facebook.com/"><i class="fa fa-facebook"></i></a>
    <a href="https://twitter.com/?lang=fr"><i class="fa fa-twitter"></i></a>
  </span>

  <span class="footer-right">@FootHacker, Inc.</span>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logo.png" %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <!-- Search form -->


    <!-- Different navigation if login or not -->
    <% if user_signed_in? %>

      <!-- Notification -->
     <!--  -->

      <!-- Profile picture and dropdown -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= image_tag current_user.facebook_picture_url || "paulo.jpg", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to edit_profile_path(current_user.profile) do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %>
            </li>
            <li>
              <%= link_to games_path do %>
                <i class="fa fa-star" aria-hidden="true"></i> <%= t(".profile", default: "Games") %>

              <% end %>
            </li>
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-home"></i>  <%= t(".profile", default: "Home") %>

              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>

              <% end %>
            </li>
          </ul>
        </div>
      </div>

    <% else %>

      <!-- Login text link -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>

      <%= link_to t(".sign_up", default: "Sign Up"), new_user_registration_path, class: "navbar-wagon-item navbar-wagon-link" %>

    <% end %>

    <!-- Button (call-to-action) -->

  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>